<?php

require_once __DIR__ . '/../config/Database.php';

use App\Config\Database;

function seedDatabase(): void {
    $pdo = Database::getConnection();

    // 1. Clear existing data
    $driver = Database::getActiveDriver();
    if ($driver === 'mysql') {
        $pdo->exec("SET FOREIGN_KEY_CHECKS = 0;");
    }

    $pdo->exec("DELETE FROM reviews;");
    $pdo->exec("DELETE FROM order_items;");
    $pdo->exec("DELETE FROM orders;");
    $pdo->exec("DELETE FROM addresses;");
    $pdo->exec("DELETE FROM users;");
    $pdo->exec("DELETE FROM products;");
    $pdo->exec("DELETE FROM categories;");
    $pdo->exec("DELETE FROM coupons;");

    if ($driver === 'mysql') {
        $pdo->exec("SET FOREIGN_KEY_CHECKS = 1;");
    }

    // 2. Insert Categories
    $categories = [
        ['id' => 'all', 'name' => 'All', 'icon' => 'grid_view_rounded', 'description' => 'Browse our complete luxury curated catalog', 'accent_color' => '0xFFFF2D6F', 'badge' => 'TOP'],
        ['id' => 'apparel', 'name' => 'Apparel', 'icon' => 'checkroom_rounded', 'description' => 'Designer streetwear, hoodies, linen shirts & tailored outerwear', 'accent_color' => '0xFFFF2D6F', 'badge' => 'NEW'],
        ['id' => 'accessories', 'name' => 'Accessories', 'icon' => 'watch_rounded', 'description' => 'Sapphire timepieces, titanium eyewear & leather goods', 'accent_color' => '0xFF6C63FF', 'badge' => 'HOT'],
        ['id' => 'footwear', 'name' => 'Footwear', 'icon' => 'snowshoeing_rounded', 'description' => 'Cushioned foam runners, leather low-tops & loafers', 'accent_color' => '0xFF10B981', 'badge' => 'SALE'],
        ['id' => 'electronics', 'name' => 'Electronics', 'icon' => 'headphones_rounded', 'description' => 'Active noise cancelling audio, wearables & smart home', 'accent_color' => '0xFF3B82F6', 'badge' => 'PRO'],
        ['id' => 'bags', 'name' => 'Bags', 'icon' => 'work_outline_rounded', 'description' => 'Full-grain leather duffels, waterproof city backpacks & totes', 'accent_color' => '0xFFF59E0B', 'badge' => 'LUXE'],
        ['id' => 'jewelry', 'name' => 'Jewelry', 'icon' => 'diamond_outlined', 'description' => '18K gold vermeil, sterling silver rings & handcrafted pendants', 'accent_color' => '0xFFEC4899', 'badge' => 'FINE'],
    ];

    $catStmt = $pdo->prepare("INSERT INTO categories (id, name, icon, description, accent_color, badge) VALUES (:id, :name, :icon, :description, :accent_color, :badge)");
    foreach ($categories as $cat) {
        $catStmt->execute($cat);
    }

    // 3. Insert Products
    $products = [
        [
            'id' => 1,
            'name' => 'Oversized Heavyweight Cotton Hoodie',
            'brand' => 'StreetLab',
            'category' => 'Apparel',
            'price' => 64.99,
            'original_price' => 89.99,
            'rating' => 4.8,
            'reviews_count' => 142,
            'image_url' => 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
            'description' => 'Crafted from ultra-soft 450 GSM French terry cotton with drop-shoulders and double-layered hood.',
            'sizes' => '["S", "M", "L", "XL", "XXL"]',
            'colors' => '["#1E1E2F", "#D64545", "#4A90E2", "#333333"]',
            'specs' => '{"Material": "100% Organic Heavyweight Cotton", "Fit": "Relaxed Oversized Fit", "Care": "Machine wash cold", "Origin": "Portugal"}',
            'badge' => 'SALE',
            'in_stock' => 1,
        ],
        [
            'id' => 2,
            'name' => 'Tailored Linen Resort Shirt',
            'brand' => 'Riviera',
            'category' => 'Apparel',
            'price' => 49.99,
            'original_price' => 69.99,
            'rating' => 4.6,
            'reviews_count' => 74,
            'image_url' => 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
            'description' => 'Lightweight 100% French flax linen shirt designed with open camp collar and mother-of-pearl buttons.',
            'sizes' => '["S", "M", "L", "XL"]',
            'colors' => '["#F0EAD6", "#87CEEB", "#E6E6FA", "#2E4053"]',
            'specs' => '{"Fabric": "100% French Flax Linen", "Collar": "Cuban / Camp Collar", "Wash": "Pre-washed for softness"}',
            'badge' => 'NEW',
            'in_stock' => 1,
        ],
        [
            'id' => 3,
            'name' => 'Minimalist Cargo Jogger Pants',
            'brand' => 'UrbanCraft',
            'category' => 'Apparel',
            'price' => 59.0,
            'original_price' => 79.0,
            'rating' => 4.7,
            'reviews_count' => 89,
            'image_url' => 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80',
            'description' => 'Stretch cotton twill cargo joggers with tapered ankles, ergonomic gusset, and low-profile magnetic pockets.',
            'sizes' => '["30", "32", "34", "36"]',
            'colors' => '["#2F4F4F", "#1A1A1A", "#556B2F"]',
            'specs' => '{"Material": "98% Cotton, 2% Elastane Twill", "Pockets": "6 Utility Pockets"}',
            'badge' => 'HOT',
            'in_stock' => 1,
        ],
        [
            'id' => 4,
            'name' => 'Premium Wool Cashmere Knit Sweater',
            'brand' => 'Aura',
            'category' => 'Apparel',
            'price' => 129.0,
            'original_price' => 169.0,
            'rating' => 4.9,
            'reviews_count' => 115,
            'image_url' => 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80',
            'description' => 'Luxurious 70% Merino wool and 30% Mongolian cashmere blend crewneck sweater with ribbed trim.',
            'sizes' => '["S", "M", "L", "XL"]',
            'colors' => '["#D2B48C", "#2F4F4F", "#800000", "#1C2833"]',
            'specs' => '{"Composition": "70% Merino Wool, 30% Cashmere", "Origin": "Italy"}',
            'badge' => 'LUXE',
            'in_stock' => 1,
        ],
        [
            'id' => 5,
            'name' => 'Vintage Wash Denim Trucker Jacket',
            'brand' => 'Heritage Denim',
            'category' => 'Apparel',
            'price' => 89.5,
            'original_price' => 119.5,
            'rating' => 4.7,
            'reviews_count' => 68,
            'image_url' => 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
            'description' => '13.5 oz selvedge denim jacket featuring antique copper hardware and custom hand-distressed wash.',
            'sizes' => '["M", "L", "XL"]',
            'colors' => '["#4682B4", "#2B3856", "#111111"]',
            'specs' => '{"Denim Weight": "13.5 oz Selvedge", "Hardware": "Custom Copper Shanks"}',
            'badge' => 'TRENDING',
            'in_stock' => 1,
        ],
        [
            'id' => 6,
            'name' => 'Classic Heavy Cotton Graphic Tee',
            'brand' => 'StreetLab',
            'category' => 'Apparel',
            'price' => 34.0,
            'original_price' => 45.0,
            'rating' => 4.8,
            'reviews_count' => 210,
            'image_url' => 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
            'description' => '240 GSM single jersey cotton tee with ribbed crew neck and screen-printed typography on back.',
            'sizes' => '["S", "M", "L", "XL", "XXL"]',
            'colors' => '["#FFFFFF", "#111111", "#808080"]',
            'specs' => '{"Weight": "240 GSM", "Fit": "Boxy Regular Fit"}',
            'badge' => 'BESTSELLER',
            'in_stock' => 1,
        ],
        [
            'id' => 7,
            'name' => 'Waterproof Technical Rain Parka',
            'brand' => 'Velocity',
            'category' => 'Apparel',
            'price' => 149.0,
            'original_price' => 199.0,
            'rating' => 4.9,
            'reviews_count' => 56,
            'image_url' => 'https://images.unsplash.com/photo-1544923246-77307dd654cb?auto=format&fit=crop&w=800&q=80',
            'description' => '3-layer seam-sealed breathable shell with 20,000mm waterproof rating and storm hood.',
            'sizes' => '["S", "M", "L", "XL"]',
            'colors' => '["#000000", "#556B2F", "#D4AF37"]',
            'specs' => '{"Waterproof": "20,000mm Hydrostatic", "Zippers": "YKK Aquaguard"}',
            'badge' => 'PRO',
            'in_stock' => 1,
        ],
        [
            'id' => 8,
            'name' => 'Tailored Slim Fit Chino Trousers',
            'brand' => 'Riviera',
            'category' => 'Apparel',
            'price' => 54.0,
            'original_price' => 75.0,
            'rating' => 4.6,
            'reviews_count' => 130,
            'image_url' => 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=800&q=80',
            'description' => 'Modern slim cut crafted from Italian stretch cotton gabardine with horn buttons.',
            'sizes' => '["30", "32", "34", "36"]',
            'colors' => '["#C2B280", "#1C2833", "#708090"]',
            'specs' => '{"Material": "97% Cotton, 3% Elastane", "Closure": "Zip fly with button tab"}',
            'badge' => 'ESSENTIAL',
            'in_stock' => 1,
        ],
        [
            'id' => 9,
            'name' => 'Lightweight Quilted Puffer Vest',
            'brand' => 'UrbanCraft',
            'category' => 'Apparel',
            'price' => 79.99,
            'original_price' => 109.99,
            'rating' => 4.7,
            'reviews_count' => 48,
            'image_url' => 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=800&q=80',
            'description' => '700-fill power recycled down vest with water-repellent micro-ripstop shell.',
            'sizes' => '["M", "L", "XL"]',
            'colors' => '["#111111", "#2E4053", "#8B4513"]',
            'specs' => '{"Fill": "700 FP Recycled Down", "Shell": "Recycled DWR Nylon"}',
            'badge' => 'SALE',
            'in_stock' => 1,
        ],
        [
            'id' => 10,
            'name' => 'Brushed Flannel Overshirt',
            'brand' => 'Heritage Denim',
            'category' => 'Apparel',
            'price' => 62.0,
            'original_price' => 85.0,
            'rating' => 4.8,
            'reviews_count' => 92,
            'image_url' => 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
            'description' => 'Heavyweight double-brushed 100% cotton flannel with dual chest flap pockets.',
            'sizes' => '["S", "M", "L", "XL"]',
            'colors' => '["#B22222", "#2E4053", "#228B22"]',
            'specs' => '{"Fabric": "Heavyweight Brushed Cotton", "Fit": "Layering Relaxed"}',
            'badge' => 'WARM',
            'in_stock' => 1,
        ],
        [
            'id' => 11,
            'name' => 'Athletic Training Quick-Dry Shorts',
            'brand' => 'Velocity',
            'category' => 'Apparel',
            'price' => 38.0,
            'original_price' => 48.0,
            'rating' => 4.9,
            'reviews_count' => 164,
            'image_url' => 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=800&q=80',
            'description' => '5-inch inseam 4-way stretch shorts with built-in compression liner and zipper phone pocket.',
            'sizes' => '["S", "M", "L", "XL"]',
            'colors' => '["#111111", "#4169E1", "#808080"]',
            'specs' => '{"Inseam": "5 Inches", "Liner": "Antimicrobial Compression"}',
            'badge' => 'FIT',
            'in_stock' => 1,
        ],
        [
            'id' => 12,
            'name' => 'Double-Breasted Wool Overcoat',
            'brand' => 'Aura',
            'category' => 'Apparel',
            'price' => 249.0,
            'original_price' => 329.0,
            'rating' => 4.9,
            'reviews_count' => 42,
            'image_url' => 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
            'description' => 'Impeccably tailored long wool trench coat with peak lapels, horn buttons, and silky cupro lining.',
            'sizes' => '["38R", "40R", "42R", "44R"]',
            'colors' => '["#1C2833", "#C2B280", "#2F4F4F"]',
            'specs' => '{"Material": "100% Virgin Wool", "Lining": "100% Cupro Bemberg"}',
            'badge' => 'EXCLUSIVE',
            'in_stock' => 1,
        ],
        [
            'id' => 13,
            'name' => 'AeroBoost Carbon Mesh Runners',
            'brand' => 'Velocity',
            'category' => 'Footwear',
            'price' => 119.5,
            'original_price' => 149.5,
            'rating' => 4.7,
            'reviews_count' => 98,
            'image_url' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
            'description' => 'Ultra-responsive carbon fiber plate running shoes with breathable seamless engineered mesh.',
            'sizes' => '["8", "9", "10", "11", "12"]',
            'colors' => '["#D64545", "#111111", "#FFFFFF"]',
            'specs' => '{"Weight": "210g (Size 9)", "Drop": "8mm", "Plate": "Full-length Carbon Fiber"}',
            'badge' => 'HOT',
            'in_stock' => 1,
        ],
        [
            'id' => 14,
            'name' => 'Minimalist White Leather Low-Tops',
            'brand' => 'StreetLab',
            'category' => 'Footwear',
            'price' => 110.0,
            'original_price' => 135.0,
            'rating' => 4.9,
            'reviews_count' => 230,
            'image_url' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
            'description' => 'Full-grain Italian calfskin leather sneakers with stitched Margom rubber cupsole.',
            'sizes' => '["7", "8", "9", "10", "11", "12"]',
            'colors' => '["#FFFFFF", "#F5F5DC"]',
            'specs' => '{"Upper": "Italian Nappa Leather", "Sole": "Stitched Margom Rubber"}',
            'badge' => 'BESTSELLER',
            'in_stock' => 1,
        ],
        [
            'id' => 15,
            'name' => 'Italian Suede Penny Loafers',
            'brand' => 'Riviera',
            'category' => 'Footwear',
            'price' => 165.0,
            'original_price' => 220.0,
            'rating' => 4.8,
            'reviews_count' => 61,
            'image_url' => 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=800&q=80',
            'description' => 'Handcrafted in Florence from butter-soft suede with Blake-stitched leather sole.',
            'sizes' => '["8", "9", "10", "11"]',
            'colors' => '["#8B4513", "#2F4F4F", "#1C2833"]',
            'specs' => '{"Leather": "Florence Suede", "Construction": "Blake Stitched"}',
            'badge' => 'LUXE',
            'in_stock' => 1,
        ],
        [
            'id' => 16,
            'name' => 'Retro High-Top Basketball Sneakers',
            'brand' => 'StreetLab',
            'category' => 'Footwear',
            'price' => 125.0,
            'original_price' => 160.0,
            'rating' => 4.7,
            'reviews_count' => 118,
            'image_url' => 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80',
            'description' => 'Iconic silhouette featuring padded ankle collars, perforated toe box, and vintage off-white midsole.',
            'sizes' => '["8", "9", "10", "11", "12", "13"]',
            'colors' => '["#111111", "#B22222", "#4169E1"]',
            'specs' => '{"Upper": "Premium Full Grain Leather", "Cushioning": "Air Cushion Unit"}',
            'badge' => 'TRENDING',
            'in_stock' => 1,
        ],
        [
            'id' => 17,
            'name' => 'Waterproof Trail Hiking Boots',
            'brand' => 'UrbanCraft',
            'category' => 'Footwear',
            'price' => 175.0,
            'original_price' => 225.0,
            'rating' => 4.9,
            'reviews_count' => 84,
            'image_url' => 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80',
            'description' => 'Rugged Nubuck leather boots with waterproof eVent membrane and Vibram Megagrip lug sole.',
            'sizes' => '["8", "9", "10", "11", "12"]',
            'colors' => '["#556B2F", "#8B4513", "#2E4053"]',
            'specs' => '{"Membrane": "eVent Waterproof", "Outsole": "Vibram Megagrip 5mm Lugs"}',
            'badge' => 'PRO',
            'in_stock' => 1,
        ],
        [
            'id' => 18,
            'name' => 'Classic Leather Chelsea Boots',
            'brand' => 'Aura',
            'category' => 'Footwear',
            'price' => 185.0,
            'original_price' => 240.0,
            'rating' => 4.8,
            'reviews_count' => 95,
            'image_url' => 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&w=800&q=80',
            'description' => 'Timeless pull-on Chelsea boots with elastic side gussets and Goodyear-welted Dainite rubber sole.',
            'sizes' => '["8", "9", "10", "11", "12"]',
            'colors' => '["#111111", "#8B4513", "#D2B48C"]',
            'specs' => '{"Construction": "Goodyear Welted", "Sole": "Dainite Studded Rubber"}',
            'badge' => 'ESSENTIAL',
            'in_stock' => 1,
        ],
        [
            'id' => 19,
            'name' => 'CloudFoam Ergonomic Slide Sandals',
            'brand' => 'Velocity',
            'category' => 'Footwear',
            'price' => 32.0,
            'original_price' => 42.0,
            'rating' => 4.6,
            'reviews_count' => 180,
            'image_url' => 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=800&q=80',
            'description' => 'One-piece molded EVA slides offering superior arch support and waterproof recovery cushioning.',
            'sizes' => '["7", "8", "9", "10", "11"]',
            'colors' => '["#111111", "#D3D3D3", "#556B2F"]',
            'specs' => '{"Material": "Dual-Density EVA Foam", "Waterproof": "100% Water Resistant"}',
            'badge' => 'SALE',
            'in_stock' => 1,
        ],
        [
            'id' => 20,
            'name' => 'Chunky Platform Knit Runners',
            'brand' => 'StreetLab',
            'category' => 'Footwear',
            'price' => 95.0,
            'original_price' => 130.0,
            'rating' => 4.7,
            'reviews_count' => 66,
            'image_url' => 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
            'description' => 'Futuristic sock-knit upper with exaggerated sculpted foam sole and TPU heel clip.',
            'sizes' => '["6", "7", "8", "9", "10"]',
            'colors' => '["#F5F5F5", "#111111", "#FF69B4"]',
            'specs' => '{"Upper": "Engineered FlyKnit", "Midsole": "Sculpted EVA Platform"}',
            'badge' => 'HOT',
            'in_stock' => 1,
        ],
        [
            'id' => 21,
            'name' => 'Aura Pro ANC Wireless Headphones',
            'brand' => 'SonicLabs',
            'category' => 'Electronics',
            'price' => 189.0,
            'original_price' => 249.0,
            'rating' => 4.9,
            'reviews_count' => 312,
            'image_url' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
            'description' => 'Studio-grade sound with 40mm beryllium drivers, 45dB ANC, and 50-hour battery life.',
            'sizes' => '["Standard"]',
            'colors' => '["#111111", "#Silver", "#Midnight Blue"]',
            'specs' => '{"Driver Size": "40mm Beryllium", "Battery": "50 Hours", "Bluetooth": "Bluetooth 5.3 LDAC"}',
            'badge' => 'POPULAR',
            'in_stock' => 1,
        ],
        [
            'id' => 22,
            'name' => 'OLED Smart Fitness Tracker Watch',
            'brand' => 'TechVibe',
            'category' => 'Electronics',
            'price' => 129.99,
            'original_price' => 169.99,
            'rating' => 4.7,
            'reviews_count' => 89,
            'image_url' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
            'description' => '1.43-inch AMOLED display with ECG, SpO2 sensor, GPS, and 14-day battery life.',
            'sizes' => '["40mm", "44mm"]',
            'colors' => '["#000000", "#C0C0C0", "#FFD700"]',
            'specs' => '{"Display": "1.43\" AMOLED 466x466", "Waterproof": "5ATM (50m)", "Battery": "14 Days Typical"}',
            'badge' => 'NEW',
            'in_stock' => 1,
        ],
        [
            'id' => 23,
            'name' => 'True Wireless Spatial Audio Earbuds',
            'brand' => 'SonicLabs',
            'category' => 'Electronics',
            'price' => 89.0,
            'original_price' => 120.0,
            'rating' => 4.8,
            'reviews_count' => 178,
            'image_url' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
            'description' => 'Dynamic spatial head-tracking with active noise cancellation and wireless charging case.',
            'sizes' => '["Standard"]',
            'colors' => '["#FFFFFF", "#000000"]',
            'specs' => '{"ANC": "38dB Hybrid ANC", "Battery": "8h + 24h with case", "Rating": "IPX5 Water Resistant"}',
            'badge' => 'SALE',
            'in_stock' => 1,
        ],
        [
            'id' => 24,
            'name' => 'Ultra-Slim MagSafe 10,000mAh Power Bank',
            'brand' => 'VoltTech',
            'category' => 'Electronics',
            'price' => 45.0,
            'original_price' => 59.0,
            'rating' => 4.8,
            'reviews_count' => 120,
            'image_url' => 'https://images.unsplash.com/photo-1609592424368-45218d6e3c3b?auto=format&fit=crop&w=800&q=80',
            'description' => 'Magnetic 15W wireless fast charger with aluminum enclosure and USB-C 20W PD output.',
            'sizes' => '["10,000mAh"]',
            'colors' => '["#111111", "#708090"]',
            'specs' => '{"Capacity": "10,000mAh Li-Polymer", "Wireless": "15W MagSafe Fast Charge"}',
            'badge' => 'HOT',
            'in_stock' => 1,
        ],
        [
            'id' => 25,
            'name' => 'Hi-Fi 360° Portable Bluetooth Speaker',
            'brand' => 'SonicLabs',
            'category' => 'Electronics',
            'price' => 79.0,
            'original_price' => 99.0,
            'rating' => 4.9,
            'reviews_count' => 215,
            'image_url' => 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
            'description' => 'Omnidirectional 30W stereo audio with deep bass radiators and IP67 waterproof floating design.',
            'sizes' => '["Compact"]',
            'colors' => '["#2E4053", "#111111", "#C0392B"]',
            'specs' => '{"Power Output": "30W Peak", "Waterproof": "IP67 Submersible", "Playtime": "20 Hours"}',
            'badge' => 'BESTSELLER',
            'in_stock' => 1,
        ],
        [
            'id' => 26,
            'name' => 'Custom Gasket Mechanical Keyboard',
            'brand' => 'TechVibe',
            'category' => 'Electronics',
            'price' => 140.0,
            'original_price' => 180.0,
            'rating' => 4.9,
            'reviews_count' => 140,
            'image_url' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
            'description' => 'CNC aluminum chassis with hot-swappable linear switches, PBT keycaps, and RGB backlighting.',
            'sizes' => '["75% Layout"]',
            'colors' => '["#1C2833", "#FDFEFE"]',
            'specs' => '{"Layout": "75% 82-Key", "Switches": "Factory Lubed Linear", "Connectivity": "Tri-mode (2.4G/BT/Type-C)"}',
            'badge' => 'PRO',
            'in_stock' => 1,
        ],
        [
            'id' => 27,
            'name' => 'Titanium Smart Health Ring',
            'brand' => 'VoltTech',
            'category' => 'Electronics',
            'price' => 199.0,
            'original_price' => 259.0,
            'rating' => 4.8,
            'reviews_count' => 77,
            'image_url' => 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
            'description' => 'Medical-grade titanium ring monitoring sleep stages, HRV, body temperature, and daily readiness.',
            'sizes' => '["Size 8", "Size 9", "Size 10", "Size 11"]',
            'colors' => '["#000000", "#Silver", "#Gold"]',
            'specs' => '{"Material": "Aerospace Titanium", "Sensors": "Optical PPG & Skin Temp", "Battery": "7 Days"}',
            'badge' => 'EXCLUSIVE',
            'in_stock' => 1,
        ],
        [
            'id' => 28,
            'name' => 'Ergonomic Aluminum Laptop Stand',
            'brand' => 'UrbanCraft',
            'category' => 'Electronics',
            'price' => 49.0,
            'original_price' => 65.0,
            'rating' => 4.8,
            'reviews_count' => 160,
            'image_url' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80',
            'description' => 'Foldable dual-axis CNC aluminum stand with silicone anti-slip grips and heat-dissipating airflow.',
            'sizes' => '["Universal 13-17\""]',
            'colors' => '["#C0C0C0", "#2F4F4F"]',
            'specs' => '{"Material": "Anodized Aluminum", "Adjustment": "360\u00b0 Height & Angle"}',
            'badge' => 'HOT',
            'in_stock' => 1,
        ],
        [
            'id' => 29,
            'name' => 'Chronograph Sapphire Ceramic Watch',
            'brand' => 'Aura',
            'category' => 'Accessories',
            'price' => 285.0,
            'original_price' => 395.0,
            'rating' => 4.9,
            'reviews_count' => 64,
            'image_url' => 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80',
            'description' => 'Swiss movement chronograph with scratch-proof sapphire crystal and ceramic tachymeter bezel.',
            'sizes' => '["41mm Case"]',
            'colors' => '["#111111", "#Silver", "#Navy Blue"]',
            'specs' => '{"Movement": "Swiss Ronda Quartz", "Glass": "Anti-Reflective Sapphire", "Water Resistance": "100M"}',
            'badge' => 'LUXE',
            'in_stock' => 1,
        ],
        [
            'id' => 30,
            'name' => 'Polarized Titanium Aviator Sunglasses',
            'brand' => 'Riviera',
            'category' => 'Accessories',
            'price' => 135.0,
            'original_price' => 175.0,
            'rating' => 4.8,
            'reviews_count' => 110,
            'image_url' => 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
            'description' => 'Featherlight titanium frames with 100% UV400 polarized mineral glass lenses.',
            'sizes' => '["Medium", "Large"]',
            'colors' => '["#FFD700", "#111111", "#C0C0C0"]',
            'specs' => '{"Frame": "Japanese Beta-Titanium", "Lens": "Polarized UV400 Category 3"}',
            'badge' => 'POPULAR',
            'in_stock' => 1,
        ],
        [
            'id' => 31,
            'name' => 'Full-Grain Leather Bi-Fold Wallet',
            'brand' => 'Heritage Denim',
            'category' => 'Accessories',
            'price' => 48.0,
            'original_price' => 65.0,
            'rating' => 4.9,
            'reviews_count' => 195,
            'image_url' => 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
            'description' => 'Vegetable-tanned Horween leather wallet with RFID blocking lining and cash slot.',
            'sizes' => '["Slim 8-Card"]',
            'colors' => '["#8B4513", "#111111", "#D2B48C"]',
            'specs' => '{"Leather": "Horween Chromexcel", "Capacity": "8-10 Cards + Cash"}',
            'badge' => 'BESTSELLER',
            'in_stock' => 1,
        ],
        [
            'id' => 32,
            'name' => 'Solid Brass Key Carabiner & Clip',
            'brand' => 'UrbanCraft',
            'category' => 'Accessories',
            'price' => 28.0,
            'original_price' => 38.0,
            'rating' => 4.7,
            'reviews_count' => 82,
            'image_url' => 'https://images.unsplash.com/photo-1614036417651-efe5912149d8?auto=format&fit=crop&w=800&q=80',
            'description' => 'Drop-forged solid brass key hook with bottle opener and titanium split ring.',
            'sizes' => '["Standard"]',
            'colors' => '["#DAA520", "#111111"]',
            'specs' => '{"Material": "Solid C360 Brass", "Weight": "45g"}',
            'badge' => 'HOT',
            'in_stock' => 1,
        ],
        [
            'id' => 33,
            'name' => 'Luxury Silk Twill Pocket Square Set',
            'brand' => 'Aura',
            'category' => 'Accessories',
            'price' => 42.0,
            'original_price' => 58.0,
            'rating' => 4.8,
            'reviews_count' => 39,
            'image_url' => 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80',
            'description' => 'Set of 3 Italian hand-rolled 100% Mulberry silk pocket squares with geometric paisley motifs.',
            'sizes' => '["33x33 cm"]',
            'colors' => '["#800020", "#1C2833", "#2E8B57"]',
            'specs' => '{"Material": "100% Mulberry Silk 16mm", "Edges": "Hand-Rolled"}',
            'badge' => 'FINE',
            'in_stock' => 1,
        ],
        [
            'id' => 34,
            'name' => 'Suede 6-Panel Baseball Cap',
            'brand' => 'StreetLab',
            'category' => 'Accessories',
            'price' => 36.0,
            'original_price' => 48.0,
            'rating' => 4.6,
            'reviews_count' => 94,
            'image_url' => 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
            'description' => 'Ultra-soft micro-suede cap with antique brass buckle and moisture-wicking sweatband.',
            'sizes' => '["Adjustable"]',
            'colors' => '["#2F4F4F", "#C2B280", "#111111"]',
            'specs' => '{"Material": "Premium Micro-Suede", "Clasp": "Brass Sliding Buckle"}',
            'badge' => 'TRENDING',
            'in_stock' => 1,
        ],
        [
            'id' => 35,
            'name' => 'Carbon Fiber MagSafe Cardholder',
            'brand' => 'VoltTech',
            'category' => 'Accessories',
            'price' => 39.0,
            'original_price' => 52.0,
            'rating' => 4.8,
            'reviews_count' => 145,
            'image_url' => 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
            'description' => 'Real 3K weave carbon fiber cardholder with pop-up quick access lever and RFID shielding.',
            'sizes' => '["Slim 5-Card"]',
            'colors' => '["#111111", "#Matte Grey"]',
            'specs' => '{"Material": "3K Carbon Fiber", "Mechanism": "Quick-Eject Lever"}',
            'badge' => 'PRO',
            'in_stock' => 1,
        ],
        [
            'id' => 36,
            'name' => 'Full Grain Leather Passport Case',
            'brand' => 'Heritage Denim',
            'category' => 'Accessories',
            'price' => 44.0,
            'original_price' => 60.0,
            'rating' => 4.9,
            'reviews_count' => 51,
            'image_url' => 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
            'description' => 'Travel companion with dedicated boarding pass slot, 4 card sleeves, and pen holder.',
            'sizes' => '["Standard Passport"]',
            'colors' => '["#8B4513", "#2E4053"]',
            'specs' => '{"Leather": "Vegetable Tanned Cowhide", "Slots": "Passport + 4 Cards + SIM Slot"}',
            'badge' => 'ESSENTIAL',
            'in_stock' => 1,
        ],
        [
            'id' => 37,
            'name' => 'Weekender Full-Grain Leather Duffel',
            'brand' => 'Aura',
            'category' => 'Bags',
            'price' => 240.0,
            'original_price' => 320.0,
            'rating' => 4.9,
            'reviews_count' => 88,
            'image_url' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
            'description' => 'Handmade 45L travel duffel with separate ventilated shoe compartment and padded shoulder strap.',
            'sizes' => '["45L Travel"]',
            'colors' => '["#8B4513", "#111111", "#D2B48C"]',
            'specs' => '{"Volume": "45 Liters", "Hardware": "Solid Brass YKK", "Shoe Compartment": "Water-resistant"}',
            'badge' => 'LUXE',
            'in_stock' => 1,
        ],
        [
            'id' => 38,
            'name' => 'Waterproof City Commuter Backpack',
            'brand' => 'UrbanCraft',
            'category' => 'Bags',
            'price' => 95.0,
            'original_price' => 130.0,
            'rating' => 4.8,
            'reviews_count' => 167,
            'image_url' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
            'description' => 'Cordura 500D ballistic nylon backpack with padded 16-inch laptop sleeve and luggage pass-through.',
            'sizes' => '["22L"]',
            'colors' => '["#111111", "#2F4F4F", "#708090"]',
            'specs' => '{"Capacity": "22 Liters", "Laptop Sleeve": "Fits up to 16\" MacBook Pro"}',
            'badge' => 'BESTSELLER',
            'in_stock' => 1,
        ],
        [
            'id' => 39,
            'name' => 'Technical Tactical Crossbody Sling',
            'brand' => 'StreetLab',
            'category' => 'Bags',
            'price' => 55.0,
            'original_price' => 75.0,
            'rating' => 4.7,
            'reviews_count' => 104,
            'image_url' => 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80',
            'description' => 'Fidlock magnetic quick-release buckle sling bag with weatherproof X-Pac fabric.',
            'sizes' => '["5L"]',
            'colors' => '["#111111", "#556B2F"]',
            'specs' => '{"Fabric": "Dimension-Polyant X-Pac", "Buckle": "Fidlock V-Buckle 25mm"}',
            'badge' => 'HOT',
            'in_stock' => 1,
        ],
        [
            'id' => 40,
            'name' => 'Structured Minimalist Leather Tote',
            'brand' => 'Riviera',
            'category' => 'Bags',
            'price' => 145.0,
            'original_price' => 195.0,
            'rating' => 4.8,
            'reviews_count' => 62,
            'image_url' => 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
            'description' => 'Vegetable-tanned calfskin leather tote with magnetic top snap and internal organizer pouch.',
            'sizes' => '["Medium (15L)"]',
            'colors' => '["#D2B48C", "#111111", "#800000"]',
            'specs' => '{"Leather": "Italian Smooth Calfskin", "Drop": "9\" Shoulder Strap"}',
            'badge' => 'NEW',
            'in_stock' => 1,
        ],
        [
            'id' => 41,
            'name' => 'Heavy-Duty Gym & Sports Duffel',
            'brand' => 'Velocity',
            'category' => 'Bags',
            'price' => 68.0,
            'original_price' => 90.0,
            'rating' => 4.7,
            'reviews_count' => 112,
            'image_url' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
            'description' => 'Ripstop polyester gym bag with water bottle holder, wet pocket, and padded base.',
            'sizes' => '["35L"]',
            'colors' => '["#111111", "#4169E1", "#808080"]',
            'specs' => '{"Volume": "35 Liters", "Pockets": "Wet Gear Isolation Compartment"}',
            'badge' => 'SALE',
            'in_stock' => 1,
        ],
        [
            'id' => 42,
            'name' => 'Leather Compact Travel Dopp Kit',
            'brand' => 'Heritage Denim',
            'category' => 'Bags',
            'price' => 38.0,
            'original_price' => 50.0,
            'rating' => 4.9,
            'reviews_count' => 140,
            'image_url' => 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
            'description' => 'Water-resistant lined washbag with dual-zipper wide opening and brass hanging loop.',
            'sizes' => '["3L"]',
            'colors' => '["#8B4513", "#111111"]',
            'specs' => '{"Lining": "Wipe-Clean Nylon", "Closure": "Dual Brass Zippers"}',
            'badge' => 'ESSENTIAL',
            'in_stock' => 1,
        ],
        [
            'id' => 43,
            'name' => 'Urban Messenger Laptop Bag',
            'brand' => 'UrbanCraft',
            'category' => 'Bags',
            'price' => 115.0,
            'original_price' => 155.0,
            'rating' => 4.8,
            'reviews_count' => 79,
            'image_url' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
            'description' => 'Waxed canvas and leather trim messenger bag with rapid strap adjust and luggage sleeve.',
            'sizes' => '["15\" Laptop"]',
            'colors' => '["#2F4F4F", "#111111"]',
            'specs' => '{"Fabric": "16 oz Martexin Waxed Canvas", "Hardware": "Solid Antique Brass"}',
            'badge' => 'PRO',
            'in_stock' => 1,
        ],
        [
            'id' => 44,
            'name' => '18K Gold Vermeil Cuban Link Chain',
            'brand' => 'Aura',
            'category' => 'Jewelry',
            'price' => 160.0,
            'original_price' => 210.0,
            'rating' => 4.9,
            'reviews_count' => 85,
            'image_url' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
            'description' => 'Hand-polished 5mm Cuban curb chain plated in 3 microns of 18-karat yellow gold over 925 silver.',
            'sizes' => '["20 Inch", "22 Inch", "24 Inch"]',
            'colors' => '["#FFD700", "#C0C0C0"]',
            'specs' => '{"Base Metal": "925 Sterling Silver", "Plating": "3 Micron 18K Gold", "Width": "5.0mm"}',
            'badge' => 'FINE',
            'in_stock' => 1,
        ],
        [
            'id' => 45,
            'name' => 'Sterling Silver Hand-Engraved Signet Ring',
            'brand' => 'Aura',
            'category' => 'Jewelry',
            'price' => 85.0,
            'original_price' => 115.0,
            'rating' => 4.8,
            'reviews_count' => 67,
            'image_url' => 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
            'description' => 'Solid 925 sterling silver cushion signet ring with hand-chiseled vintage scrollwork.',
            'sizes' => '["8", "9", "10", "11"]',
            'colors' => '["#Silver", "#Oxidized"]',
            'specs' => '{"Metal": "Solid 925 Sterling Silver", "Weight": "12.5g"}',
            'badge' => 'POPULAR',
            'in_stock' => 1,
        ],
        [
            'id' => 46,
            'name' => 'Black Onyx Geometric Pendant Necklace',
            'brand' => 'StreetLab',
            'category' => 'Jewelry',
            'price' => 75.0,
            'original_price' => 99.0,
            'rating' => 4.7,
            'reviews_count' => 54,
            'image_url' => 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
            'description' => 'Natural faceted Brazilian black onyx encased in a brushed stainless steel box pendant.',
            'sizes' => '["22 Inch Chain"]',
            'colors' => '["#111111", "#Silver"]',
            'specs' => '{"Stone": "Natural Brazilian Black Onyx", "Chain": "2.5mm Round Box Link"}',
            'badge' => 'HOT',
            'in_stock' => 1,
        ],
        [
            'id' => 47,
            'name' => 'Minimalist Matte Titanium Cuff Bracelet',
            'brand' => 'VoltTech',
            'category' => 'Jewelry',
            'price' => 68.0,
            'original_price' => 90.0,
            'rating' => 4.9,
            'reviews_count' => 43,
            'image_url' => 'https://images.unsplash.com/photo-1611591475102-7a4f91060934?auto=format&fit=crop&w=800&q=80',
            'description' => 'Hypoallergenic Grade 5 titanium open-cuff bracelet with laser-etched precision serial code.',
            'sizes' => '["Medium", "Large"]',
            'colors' => '["#111111", "#Matte Silver"]',
            'specs' => '{"Material": "Grade 5 Titanium", "Finish": "Bead-Blasted Matte"}',
            'badge' => 'PRO',
            'in_stock' => 1,
        ],
        [
            'id' => 48,
            'name' => 'Tahitian Black Pearl Drop Earrings',
            'brand' => 'Riviera',
            'category' => 'Jewelry',
            'price' => 140.0,
            'original_price' => 190.0,
            'rating' => 4.8,
            'reviews_count' => 31,
            'image_url' => 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
            'description' => 'Lustrous genuine Tahitian saltwater cultured pearls mounted on 14K white gold leverbacks.',
            'sizes' => '["10mm Pearl"]',
            'colors' => '["#000000"]',
            'specs' => '{"Pearls": "10mm Tahitian Cultured", "Findings": "14K Solid White Gold"}',
            'badge' => 'LUXE',
            'in_stock' => 1,
        ],
        [
            'id' => 49,
            'name' => 'Diamond Bezel Tennis Bracelet',
            'brand' => 'Aura',
            'category' => 'Jewelry',
            'price' => 320.0,
            'original_price' => 450.0,
            'rating' => 5.0,
            'reviews_count' => 29,
            'image_url' => 'https://images.unsplash.com/photo-1611591475102-7a4f91060934?auto=format&fit=crop&w=800&q=80',
            'description' => 'Brilliant-cut lab-grown VVS diamonds prong-set in 925 silver with double safety latch.',
            'sizes' => '["7 Inch", "7.5 Inch"]',
            'colors' => '["#Silver", "#Gold"]',
            'specs' => '{"Carat Total": "4.50 CTW", "Clarity": "VVS1-VVS2", "Color": "D-E Colorless"}',
            'badge' => 'EXCLUSIVE',
            'in_stock' => 1,
        ],
        [
            'id' => 50,
            'name' => 'Damascus Steel Hammered Band Ring',
            'brand' => 'Heritage Denim',
            'category' => 'Jewelry',
            'price' => 95.0,
            'original_price' => 130.0,
            'rating' => 4.9,
            'reviews_count' => 57,
            'image_url' => 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
            'description' => 'Hand-forged 64-layer acid-etched Damascus steel comfort-fit band with rosewood inner sleeve.',
            'sizes' => '["8", "9", "10", "11", "12"]',
            'colors' => '["#Dark Etched"]',
            'specs' => '{"Steel": "64-Layer Hand-Forged Damascus", "Inlay": "Natural African Rosewood", "Width": "8mm"}',
            'badge' => 'FINE',
            'in_stock' => 1,
        ],
    ];

    $prodStmt = $pdo->prepare("INSERT INTO products (id, name, brand, category, price, original_price, rating, reviews_count, image_url, description, sizes, colors, specs, badge, in_stock) VALUES (:id, :name, :brand, :category, :price, :original_price, :rating, :reviews_count, :image_url, :description, :sizes, :colors, :specs, :badge, :in_stock)");
    foreach ($products as $prod) {
        $prodStmt->execute($prod);
    }

    // 4. Insert Promotional Coupons
    $coupons = [
        ['code' => 'LUXE20', 'discount_type' => 'percent', 'discount_value' => 20.0, 'min_order_amount' => 50.0, 'is_active' => 1],
        ['code' => 'SAVE10', 'discount_type' => 'fixed', 'discount_value' => 10.0, 'min_order_amount' => 60.0, 'is_active' => 1],
        ['code' => 'FREESHIP', 'discount_type' => 'freeship', 'discount_value' => 12.0, 'min_order_amount' => 80.0, 'is_active' => 1],
        ['code' => 'VIP50', 'discount_type' => 'percent', 'discount_value' => 50.0, 'min_order_amount' => 200.0, 'is_active' => 1],
    ];

    $coupStmt = $pdo->prepare("INSERT INTO coupons (code, discount_type, discount_value, min_order_amount, is_active) VALUES (:code, :discount_type, :discount_value, :min_order_amount, :is_active)");
    foreach ($coupons as $coup) {
        $coupStmt->execute($coup);
    }

    // 5. Seed Demo User
    $demoPassword = password_hash('password123', PASSWORD_BCRYPT);
    $userStmt = $pdo->prepare("INSERT INTO users (id, name, email, password_hash, phone, role) VALUES (:id, :name, :email, :password_hash, :phone, :role)");
    $userStmt->execute([
        'id' => 'usr_1',
        'name' => 'Demo Customer',
        'email' => 'customer@luxecart.com',
        'password_hash' => $demoPassword,
        'phone' => '+1 (555) 234-5678',
        'role' => 'customer',
    ]);

    echo "[SEED SUCCESS] Database seeded with " . count($categories) . " categories, " . count($products) . " products, " . count($coupons) . " coupons, and 1 demo user.\n";
}

if (php_sapi_name() === 'cli' && basename(__FILE__) === basename($_SERVER['PHP_SELF'])) {
    seedDatabase();
}
